CREATE SCHEMA IF NOT EXISTS security;
CREATE SCHEMA IF NOT EXISTS rolesandpermissions;
CREATE SCHEMA IF NOT EXISTS academic;
CREATE SCHEMA IF NOT EXISTS environments;
CREATE SCHEMA IF NOT EXISTS schedules;
CREATE SCHEMA IF NOT EXISTS facialrecognition;
CREATE SCHEMA IF NOT EXISTS notifications;
CREATE SCHEMA IF NOT EXISTS legal;
